### ISSUE TITLE
Game crash whislt initializing

### ISSUE THREAD

**Issue by KRYFl** [LolHens/mc-fluid-physics#11]
**All the issue in report file:**

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 03/10/20 16:23
Description: Initializing game

java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.util.registry.Registry
	at net.minecraft.item.ItemStack.lambda$static$3(ItemStack.java:77) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack$$Lambda$1164/1454366618.apply(Unknown Source) ~[?:?] {}
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.item.ItemStack.<clinit>(ItemStack.java:76) ~[?:?] {re:classloading}
	at net.minecraft.client.settings.HotbarSnapshot.<init>(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.client.settings.CreativeSettings.<init>(SourceFile:30) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:394) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.61.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$391/36627152.call(Unknown Source) [forge-1.16.2-33.0.61.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.item.ItemStack.lambda$static$3(ItemStack.java:77) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack$$Lambda$1164/1454366618.apply(Unknown Source) ~[?:?] {}
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.item.ItemStack.<clinit>(ItemStack.java:76) ~[?:?] {re:classloading}
	at net.minecraft.client.settings.HotbarSnapshot.<init>(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.client.settings.CreativeSettings.<init>(SourceFile:30) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:394) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.61.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$391/36627152.call(Unknown Source) [forge-1.16.2-33.0.61.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 132853952 bytes (126 MB) / 234881024 bytes (224 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.2-forge-33.0.61
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by LolHens** [comment]
Thank you! I tried to reproduce this crash but wasn't able to yet.
Could you post a list of mods you have installed?

**Comment by KRYFl** [comment]
Zero. Just forge and your mod:
![image](https://user-images.githubusercontent.com/46136925/95024994-e5608d00-065c-11eb-9951-c29ac02d3187.png)

**Comment by KRYFl** [comment]
![bandicam-2020-10-04-16-19-51-157](https://user-images.githubusercontent.com/46136925/95025140-1db49b00-065e-11eb-94d5-96ce039a2c89.gif)

**Comment by LolHens** [comment]
Ohhhh! You have to install https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force as it is a required dependency.
That error message is really confusing though. Maybe I can do something about that.

**Comment by KRYFl** [comment]
Well, it work! Ty <3
