### ISSUE TITLE
crash when loading game

### ISSUE THREAD

**Issue by 1a2s3d4f1** [LolHens/mc-fluid-physics#4]
The game was crash when I updated this mod to 1.2.1
NO config file(I was use 1.0.1 version)
crash report:
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2020-07-26 22:46:54 GMT+08:00
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'fluidphysics'
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.21)
    at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
    at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$ben000$stopFabricInit(MinecraftClient:11291)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:425)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at net.fabricmc.language.scala.ScalaLanguageAdapter.create(ScalaLanguageAdapter.scala:26)
    at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
    at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
    at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186)
    ... 13 more
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.util.DefaultLanguageAdapter$1.invoke(DefaultLanguageAdapter.java:122)
    at com.sun.proxy.$Proxy25.equals(Unknown Source)
    at de.lolhens.fluidphysics.FluidPhysicsMod$.$anonfun$metadata$1(FluidPhysicsMod.java:20)
    at de.lolhens.fluidphysics.FluidPhysicsMod$.$anonfun$metadata$1$adapted(FluidPhysicsMod.java:20)
    at scala.collection.IterableOnceOps.find(IterableOnce.scala:610)
    at scala.collection.IterableOnceOps.find$(IterableOnce.scala:606)
    at scala.collection.AbstractIterator.find(Iterator.scala:1274)
    at de.lolhens.fluidphysics.FluidPhysicsMod$.<clinit>(FluidPhysicsMod.java:20)
    ... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.16.1
  Minecraft Version ID: 1.16.1
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_252, BellSoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
  Memory: 260390272 bytes (248 MB) / 1561329664 bytes (1489 MB) up to 2621440000 bytes (2500 MB)
  CPUs: 4
  JVM Flags: 3 total; -XX:+UseG1GC -Xmx2500m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  Suspected Mods: Fabric Loader (fabricloader), Fabric Language Scala (fabric-language-scala)
  Fabric Mods: adabraniummod: Adabranium Mod 1.1.5.1
               adorn: Adorn 1.9.1+1.16.1
               advancements-enlarger: Advancements Enlarger 0.2.2
               adventurez: AdventureZ 1.0.6
               amecs: Amecs 1.3.0+mc.1.16.1
               amecsapi: Amecs API 1.0.2+1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               appleskin: AppleSkin 1.0.11
               artifice: Artifice 0.8.0+1.16-rc1
               artofalchemy: Art of Alchemy 1.0.0-rc2+1.16.1
               astromine: Astromine 1.3.5
               autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
               autoharvest: autoharvest 1.0.5
               autoswitch: AutoSwitch 2.7.1
               autoswitch-api: AutoSwitch API 1.0.0
               bambootweaks: Bamboo Tweaks unspecified
               banner_capes: Banner Capes 0.2.1
               beachslimes: Beach Slimes 2.1.0+mc1.16.1
               betterdroppeditems: Better Dropped Items 1.2.1-1.16
               biom4st3r_incense: Campfire Incense 0.6.0
               blockus: Blockus 1.6.2
               blue_endless_jankson: jankson +
               boringbackgrounds: Boring Backgrounds 2.1.0-1.16.pre3
               bunch-o-trinkets: Bunch O' Trinkets 1.0.1
               campanion: Campanion 1.1.12+build.33
               cardinal-components: Cardinal Components API 2.4.2
               cardinal-components-base: Cardinal Components API (base) 2.4.2
               cardinal-components-block: Cardinal Components API (blocks) 2.4.2
               cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
               cardinal-components-entity: Cardinal Components API (entities) 2.4.2
               cardinal-components-item: Cardinal Components API (items) 2.4.2
               cardinal-components-level: Cardinal Components API (world saves) 2.4.2
               cardinal-components-util: Cardinal Components API (utilities) 2.4.2
               cardinal-components-world: Cardinal Components API (worlds) 2.4.2
               cavebiomes: Cave Biomes 0.2.3
               chainmail: Chainmail 0.3.0
               chunkpregen: Fabric Chunk Pregenerator 0.2.2
               cinderscapes: Cinderscapes 1.0.5+build.36-1.16.1
               cleancut: CleanCut mc1.16-2.1-fabric
               cleardespawn: Clear Despawn 1.16-fabric0.13.1-1.1.1
               cloth-api: Cloth API 1.0.6
               cloth-armor-api-v1: Cloth Armor API v1 1.0.6
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.0.6
               cloth-common-events-v1: Cloth Common Events v1 1.0.6
               cloth-config2: Cloth Config v4 4.6.0
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.6
               cloth-scissors-api-v1: Cloth Scissors API v1 1.0.6
               cloth-utils-v1: Cloth Utils v1 1.0.6
               colorunchained: Color Unchained 1.1.0-1.16.1
               com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               com_squareup_moshi_moshi: moshi 1.9.2
               com_squareup_okio_okio: okio 1.16.0
               compressedblocks: Compressed Blocks 1.0
               connected_block_textures: Connected Block Textures 0.1.0+1.16
               cotton: Cotton 1.0.6
               cotton-cauldron: Cotton Cauldron 1.0.4
               cotton-commons: Cotton Commons 1.0.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-datapack: Cotton Datapack 1.0.6
               cotton-logging: Cotton Logging 1.0.0-rc.4
               cotton-player-events: Cotton Player Events 1.0.2
               couplings: Couplings 1.3.1
               creativebuttonmover: Creative Button Mover 0.2.5
               crookedcrooks: Crooked Crooks 1.2.1+1.16.1
               crusade: Crudade Mod 1.1.2
               curios: Curios API 1.16.1-0.2
               customskinloader: CustomSkinLoader 14.12
               darkness: True Darkness 1.5.43
               decorative: Decorative 2.0.0 - Summer 2020 Update
               diggusmaximus: Diggus Maximus 1.3.0-1.16
               dishes: Delicious Dishes 1.0.3
               dynamicfps: Dynamic FPS 1.1.4
               dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
               ecotones: Ecotones 0.4.4
               endreborn: End: Rebellion 1.5
               expandedstorage: ExpandedStorage 5.3.15
               experimentaway: ExperimentAway 1.0.0
               fabric: Fabric API 0.16.0+build.384-1.16.1
               fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
               fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
               fabric-diagonal-panes: Fabric Diagonal Panes 0.3.0
               fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030fb0
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
               fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
               fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5b0
               fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
               fabric-language-scala: Fabric Language Scala 0.3.2.12
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
               fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
               fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
               fabricloader: Fabric Loader 0.9.0+build.204
               fatxporbs: Fat Experience Orbs 0.0.7
               fiber: fiber 0.23.0-1
               flesh2leather: Flesh2Leather 1.0.0
               flonters: Flonters 1.1.0+1.16.1
               flora-doubling: Flora Doubling 1.1.1
               fluidphysics: Fluid Physics 1.2.1
               gameinfo: GameInfo 2.0.0a-experimental-06 1.16.1
               gamemodeoverhaul: GamemodeOverhaul 1.16.1-1.0.1.8
               gbfabrictools: GBfabrictools 1.2.2+1.16
               givemehats: Give Me Hats! 1.0.0
               glassdoor: Glass Doors 1.4.4-1.16
               glassential: Glassential 1.16.1-1.1.4
               godown: Go Down 0.2.0+1.16.1
               golemsgalore: Golems Galore 0.1.4+mc.1.16.1
               gravestones: Gravestones 1.4.0
               hard-hat-steve: Hard Hat Steve 1.1.1
               harvest: Harvest 1.2.12
               hctm-base: HCTM Base 3.4.0
               healthoverlay: Health Overlay 3.6.12
               held-item-info: Held Item Info 1.1.2
               herbocraft: Herbocraft dev
               identity: Identity 1.4.0-beta-1.16
               iknowwhatimdoing: I Know What I'm Doing 3.0.0
               improved-stations: Improved Stations 2.0.2-unstable
               indrev: Industrial Revolution 1.4.0-BETA
               inventoryprofiles: Inventory Profiles 0.4.2
               iron-jetpacks: Iron Jetpacks 0.2.5
               item-pickup-customization: Item Pickup Customization 1.1.1-1.16.1
               jankson: Jankson 3.0.0+j1.2.0
               jumploader: Jumploader 2.0.0
               kibe: Kibe 1.1.11-BETA
               kubejs: KubeJS 1.1.1
               kyrptconfig: Kytpt Config 1.1.0-1.16
               leafmealone: Leaf Me Alone 2.1
               lettuce: Lettuce Not Crash 1.0
               libaddict: libaddict 0.2.1
               libblockattributes: LibBlockAttributes 0.7.1-pre.4
               libblockattributes_core: LibBlockAttributes (Core) 0.7.1-pre.4
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.1-pre.4
               libblockattributes_items: LibBlockAttributes (Items) 0.7.1-pre.4
               libcd: LibCapableData 2.5.0+1.16.1
               libgamerule: LibGamerule ${version}
               libgui: LibGui 2.2.0+1.16.1
               libmultipart: LibMultiPart 0.4.0
               libnetworkstack: Lib Network Stack 0.4.0
               libstructure: Libstructure 1.3
               lightoverlay: Light Overlay 5.4.1
               linkart: Linkart unspecified
               linkedstorage: Linked Storage 1.3.5-1.16
               lithium: Lithium 0.5.1
               loadcatcher: Entrypoint Catcher 2.0.0
               ltr: LilTaterReloaded 1.1.7+1.16.1
               lvmnt: SuperAxes 1.1.4
               magna: Magna 1.1.2-1.16.1
               mambience: MAmbience 2.1.0-1.16
               mcf-reap: MaxVar reap for fabric 1.4.0
               mechanized: Mechanized 1.9.5
               minecraft: Minecraft 1.16.1
               minime_paperdoll: Player Mini-Me (Paper Doll) 1.0.4
               mixedslab: Mixed Slab 1.16.1-fabric-1.1.0.1
               mm: Manningham Mills 2.0
               mmorpg: Age of Exile 1.0.2
               mo_glass: Mo Glass 1.3-MC1.16.1
               modid: Catch Me If You Can! 1.0.0
               modmenu: Mod Menu 1.14.5+build.30
               modupdater: ModUpdater 1.1.8+1.16.1
               moreberries: More Berries 1.3.1
               morepaths: More Paths 0.0.2
               mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
               mousewheelie: Mouse Wheelie 1.5.0+mc1.16.1
               ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.4
               notenoughcrashes: Not Enough Crashes 2.1.0+1.16.1
               notes: Notes 1.0.1
               okzoomer: Ok Zoomer 4.0.0-alpha.4.1.16.1
               org_aeonbits_owner_owner: owner 1.0.12
               org_apache_commons_commons-compress: commons-compress 1.19
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 17.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
               org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
               org_tukaani_xz: xz 1.8
               origins: Origins 1.16-0.2.4
               packages: Packages 1.0
               parchment: Parchment 1.0.2+1.15.2
               patchouli: Patchouli 1.16-38-FABRIC
               phosphor: Phosphor 0.6.0+build.7
               piglintag: PiglinTag 1.0.0
               pigpoop: Pig Poop 1.1.3
               plantinajar: Plant In A Jar 1.2.0+1.16.1
               platos: Plato's Transporters 1.3.1.1
               playerabilitylib: Pal 1.2.0
               polymorph: Polymorph 0.0.2-1.16.1
               qcommon-cfg-core: qcommon-cfg-core 3.2.0
               qcommon-croco: Croco 2.1.1
               quickshulker: Quick Shulker 1.1.5-1.16
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               reborncore: Reborn Core 4.3.2+build.49
               repurposed_structures: Repurposed Structures 1.3.1
               respawnablepets: Respawnable Pets r3
               ringsofascension: Rings of Ascension 1.0.4
               riverredux: River Redux 0.1.4
               roughlyenoughitems: Roughly Enough Items 4.10.3
               roughlyenoughresources: Roughly Enough Resources 2.0.2
               rswires: RSWires 4.8.0
               sandwichable: Sandwichable 1.1.1-snapshot
               secretrooms: Secret Rooms 0.9.1+1.16.1
               shapes: Shapes 2.0.0+build.10
               shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
               simple_pipes: SimplePipeTest 0.4.0
               simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.4.0
               simpledrawers: Simple Drawers 1.8.0-1.16.1
               simpleteleporters: Simple Teleporters 2.2.0
               simplevoidworld: Simple Void World 4.0.0
               simplexterrain: Simplex Terrain 0.6.4
               sleepvote: SleepVote ${version}
               slight-gui-modifications: 'Slight' GUI Modifications 1.2.0
               slotlink: slotlink 0.3.6+minecraft-1.16.1
               smoothbedrock: Smooth Bedrock (Fabric) 1.2.3
               soulbound: Soulbound 1.0.1
               spark: spark 1.4.3
               spinnery: Spinnery 3.1.13
               staffofbuilding: Staff of Building 1.2.0-1.16
               step-height-entity-attribute: Step Height Entity Attribute 1.0.0
               stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
               strawdummy: Straw Dummy 1.1.0
               structurized: Structurized 1.0.0
               survivalisland: Survival Island 0.1.5
               tacocraft: TacoCraft 1.3.1+mc.1.16
               team_reborn_energy: Energy 0.1.0
               techreborn: Tech Reborn 3.4.5+build.88
               terraform: Terraform 2.1.7+build.31
               terrestria: Terrestria 2.0.4+build.50
               textile_backup: Textile Backup 1.3.1-1.16.1
               trapexpansion: Trap Expansion 1.3.2
               trash-it: Trash It 1.0.1-1.16.1
               traverse: Traverse 2.2.14+build.28
               trinkets: Trinkets 2.6.3
               tweed: Tweed API 3.0.0-beta.9
               vanilla-hammers: Vanilla Hammers 1.10.1-1.16.1
               vanillaexcavators: Vanilla Excavators 1.1.0
               vanillaplusbiomes: Vanilla Plus Biomes 0.2.2
               villagerhats: Villager Hats fabric-1.16-rc1-1.0.0
               voxelmap: VoxelMap 1.10.6
               waila: Hwyla 1.9.22
               walljump: Wall-Jump! 1.3.3+1.16.1
               whereisit: Where Is It 1.8.1
               winged: Winged Mod 1.16-1.2
               wolveswitharmor: Wolves With Armor 1.4.0-1.16.1
               woods_and_mires: Woods and Mires 1.0.0+1.16.1
  Patchouli open book context: n/a
  Launched Version: 1.16.1
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: NO CONTEXT
  GL Caps: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown>
```

**Comment by LolHens** [comment]
Thanks for the quick info. I will look at this in more detail later but for now I temporarily removed v1.2.1 from curseforge.

**Comment by LolHens** [comment]
Or does this crash also happen with 1.2.0?

**Comment by SFort** [comment]
caused by FluidPhysicsMod.scala L18-21
1.2.0 had the value set staticly so it was fine 
changing back to using a string instead of metadata would fix it

**Comment by LolHens** [comment]
Thank you for the quick analysis! I hope I can reproduce and fix this so I don't have to turn this back to using a string constant.

**Comment by LolHens** [comment]
I don't quite understand why it is crashing inside the equals method tho. Maybe changing out '==' for 'eq' would suffice?

**Comment by SFort** [comment]
while I'm not perticulary experianced in fabric/scala considering It runs fine inside an IDE but not after compiled im it's probably got something todo with the call being unavailable outside dev env.
so you would have to get the value at compile time and embed it as a string.
>is my best quess<
though looking how other mods do it seems like they just use a string

**Comment by LolHens** [comment]
Yeah maybe I should do that too. I tested this in prod and it worked so I suspect it has something to do with another mod that uses a server/client proxy. I have not tested this in a big modpack yet so that could be a problem.

**Comment by LolHens** [comment]
@1a2s3d4f1 Could you try out if this fix works for you?
https://github.com/LolHens/mc-fluid-physics/releases/download/1.2.2/fluidphysics-1.2.2.jar

**Comment by SFort** [comment]
Works when i try it

**Comment by 1a2s3d4f1** [comment]
fluid physics 1.2.2 is working ,The crash is not happen.
